In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv('train.csv')
data.head(10)

ID  Day_No  Course_ID Course_Domain Course_Type  Short_Promotion  \
0   1       1          1   Development      Course                0   
1   2       2          1   Development      Course                0   
2   3       3          1   Development      Course                0   
3   4       4          1   Development      Course                0   
4   5       5          1   Development      Course                0   
5   6       6          1   Development      Course                0   
6   7       7          1   Development      Course                1   
7   8       8          1   Development      Course                1   
8   9       9          1   Development      Course                1   
9  10      10          1   Development      Course                1   

   Public_Holiday  Long_Promotion  User_Traffic  Competition_Metric  Sales  
0               1               1         11004               0.007     81  
1               0               1         13650               0.007     79  
2               0               1         11655               0.007     75  
3               0               1         12054               0.007     80  
4               0               1          6804               0.007     41  
5               0               1         10395               0.007     62  
6               0               1         16023               0.007    122  
7               0               1         14385               0.007    114  
8               0               1         16485               0.007    121  
9               0               1         13377               0.007    100

In [3]:
data.info() #getting information about the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 512087 entries, 0 to 512086
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   ID                  512087 non-null  int64  
 1   Day_No              512087 non-null  int64  
 2   Course_ID           512087 non-null  int64  
 3   Course_Domain       512087 non-null  object 
 4   Course_Type         512087 non-null  object 
 5   Short_Promotion     512087 non-null  int64  
 6   Public_Holiday      512087 non-null  int64  
 7   Long_Promotion      512087 non-null  int64  
 8   User_Traffic        512087 non-null  int64  
 9   Competition_Metric  510323 non-null  float64
 10  Sales               512087 non-null  int64  
dtypes: float64(1), int64(8), object(2)
memory usage: 43.0+ MB


In [4]:
data.dropna(how = "all",inplace = True ) #to drop the rows have null values instead of all any can also be used
data.head(100)

ID  Day_No  Course_ID Course_Domain Course_Type  Short_Promotion  \
0     1       1          1   Development      Course                0   
1     2       2          1   Development      Course                0   
2     3       3          1   Development      Course                0   
3     4       4          1   Development      Course                0   
4     5       5          1   Development      Course                0   
..  ...     ...        ...           ...         ...              ...   
95   96      96          1   Development      Course                0   
96   97      97          1   Development      Course                0   
97   98      98          1   Development      Course                1   
98   99      99          1   Development      Course                1   
99  100     100          1   Development      Course                1   

    Public_Holiday  Long_Promotion  User_Traffic  Competition_Metric  Sales  
0                1               1         11004               0.007     81  
1                0               1         13650               0.007     79  
2                0               1         11655               0.007     75  
3                0               1         12054               0.007     80  
4                0               1          6804               0.007     41  
..             ...             ...           ...                 ...    ...  
95               0               1          6615               0.007     43  
96               0               1          7329               0.007     43  
97               0               1         15372               0.007    120  
98               0               1         14007               0.007    118  
99               0               1         16380               0.007    117  

[100 rows x 11 columns]

In [5]:
X  = data.iloc[:,0:10].values #storing the input values
Y= data.iloc[:,10].values #storing output values


In [6]:
labelencoder_X = LabelEncoder()
X[:,3] = labelencoder_X.fit_transform(X[:,3])
ct = ColumnTransformer([("Course_Domain", OneHotEncoder(), [3])],    remainder = 'passthrough')
X = ct.fit_transform(X)

In [7]:
X

array([[0.0, 1.0, 0.0, ..., 1, 11004, 0.006999999999999999],
       [0.0, 1.0, 0.0, ..., 1, 13650, 0.006999999999999999],
       [0.0, 1.0, 0.0, ..., 1, 11655, 0.006999999999999999],
       ...,
       [0.0, 0.0, 0.0, ..., 1, 13671, 0.07],
       [0.0, 0.0, 0.0, ..., 1, 8904, 0.07],
       [0.0, 0.0, 0.0, ..., 1, 11445, 0.07]], dtype=object)

In [12]:
#data["Course_Type"].fillna(1)
labelencoder_X = LabelEncoder()
X[:,4] = labelencoder_X.fit_transform(X[:,4])
ct = ColumnTransformer([("Course_Type", OneHotEncoder(), [1])],    remainder = 'passthrough')
X = ct.fit_transform(X)
X


array([[0.0, 1.0, 0.0, ..., 1, 11004, 0.006999999999999999],
       [0.0, 1.0, 0.0, ..., 1, 13650, 0.006999999999999999],
       [0.0, 1.0, 0.0, ..., 1, 11655, 0.006999999999999999],
       ...,
       [1.0, 0.0, 1.0, ..., 1, 13671, 0.07],
       [1.0, 0.0, 1.0, ..., 1, 8904, 0.07],
       [1.0, 0.0, 1.0, ..., 1, 11445, 0.07]], dtype=object)

In [13]:
data.head(10)

ID  Day_No  Course_ID Course_Domain Course_Type  Short_Promotion  \
0   1       1          1   Development      Course                0   
1   2       2          1   Development      Course                0   
2   3       3          1   Development      Course                0   
3   4       4          1   Development      Course                0   
4   5       5          1   Development      Course                0   
5   6       6          1   Development      Course                0   
6   7       7          1   Development      Course                1   
7   8       8          1   Development      Course                1   
8   9       9          1   Development      Course                1   
9  10      10          1   Development      Course                1   

   Public_Holiday  Long_Promotion  User_Traffic  Competition_Metric  Sales  
0               1               1         11004               0.007     81  
1               0               1         13650               0.007     79  
2               0               1         11655               0.007     75  
3               0               1         12054               0.007     80  
4               0               1          6804               0.007     41  
5               0               1         10395               0.007     62  
6               0               1         16023               0.007    122  
7               0               1         14385               0.007    114  
8               0               1         16485               0.007    121  
9               0               1         13377               0.007    100

In [18]:

data["Course_Type"] = '1'
data.head(10)

ID  Day_No  Course_ID Course_Domain Course_Type  Short_Promotion  \
0   1       1          1   Development           1                0   
1   2       2          1   Development           1                0   
2   3       3          1   Development           1                0   
3   4       4          1   Development           1                0   
4   5       5          1   Development           1                0   
5   6       6          1   Development           1                0   
6   7       7          1   Development           1                1   
7   8       8          1   Development           1                1   
8   9       9          1   Development           1                1   
9  10      10          1   Development           1                1   

   Public_Holiday  Long_Promotion  User_Traffic  Competition_Metric  Sales  
0               1               1         11004               0.007     81  
1               0               1         13650               0.007     79  
2               0               1         11655               0.007     75  
3               0               1         12054               0.007     80  
4               0               1          6804               0.007     41  
5               0               1         10395               0.007     62  
6               0               1         16023               0.007    122  
7               0               1         14385               0.007    114  
8               0               1         16485               0.007    121  
9               0               1         13377               0.007    100

In [19]:
training_x, test_x,training_y,test_y = train_test_split(X,Y,test_size = 0.3,random_state =0) #training and testing with testing data = 30%

In [20]:
data.head(10)


ID  Day_No  Course_ID Course_Domain Course_Type  Short_Promotion  \
0   1       1          1   Development           1                0   
1   2       2          1   Development           1                0   
2   3       3          1   Development           1                0   
3   4       4          1   Development           1                0   
4   5       5          1   Development           1                0   
5   6       6          1   Development           1                0   
6   7       7          1   Development           1                1   
7   8       8          1   Development           1                1   
8   9       9          1   Development           1                1   
9  10      10          1   Development           1                1   

   Public_Holiday  Long_Promotion  User_Traffic  Competition_Metric  Sales  
0               1               1         11004               0.007     81  
1               0               1         13650               0.007     79  
2               0               1         11655               0.007     75  
3               0               1         12054               0.007     80  
4               0               1          6804               0.007     41  
5               0               1         10395               0.007     62  
6               0               1         16023               0.007    122  
7               0               1         14385               0.007    114  
8               0               1         16485               0.007    121  
9               0               1         13377               0.007    100

In [22]:
training_x
training_y

array([134, 201, 139, ..., 110,  64,  86], dtype=int64)

ValueError: could not convert string to float: 'Course'